import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

type Section = { name: string; score: number; status: string; details: string };

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = await prisma.complianceReport.findUnique({ where: { id } });
  if (!report) return NextResponse.json({ error: "Not found" }, { status: 404 });

  let sections: Section[] = [];
  try { sections = JSON.parse(report.sections || "[]") as Section[]; } catch { sections = []; }

  const lines = [
    `COMPLIANCE REPORT: ${report.name}`,
    "=".repeat(60),
    `Type: ${report.type}`,
    `Framework: ${report.framework}`,
    `Period: ${report.period}`,
    `Date: ${report.date}`,
    `Score: ${report.score}%`,
    `Findings: ${report.findings}`,
    `Generated By: ${report.generatedBy}`,
    "",
    "EXECUTIVE SUMMARY",
    "-".repeat(40),
    report.summary,
    "",
    "DETAILED FINDINGS",
    "-".repeat(40),
    ...sections.map((s) => `\n[${String(s.status).toUpperCase()}] ${s.name} — ${s.score}%\n${s.details}`),
  ];
  const body = lines.join("\n");
  const filename = `${report.name.replace(/\s+/g, "-").toLowerCase()}.txt`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
